services:
  solid-mind:
    build: .
    container_name: solid-mind
    #ports:
    #  - "3001:3000"
    expose:
      - 3000
    volumes:
      #- data:/app/maps
      - ./data:/solid-mind/data
    restart: unless-stopped
    environment:
      TZ: Europe/London
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solid-mind.rule=Host(`solid-mind.app.internal`)"

networks:
  traefik_net:
    external: true
#volumes:
#  data:
