services:
  my-mind:
    build: .
    container_name: my-mind
    #ports:
    #  - "3001:3000"
    expose: 
      - 3000
    volumes:
      #- data:/app/maps
      - ./data:/app/maps
    restart: unless-stopped
    environment:
      TZ: Europe/London
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-mind.rule=Host(`my-mind.app.internal`)"

networks:
  traefik_net:
    external: true
#volumes:
#  data:
