services:
  my-mind:
    image: registry.internal/my-mind:latest
    #ports:
    #  - "3001:3000"
    volumes:
      - data:/app/maps
    restart: unless-stopped
    environment:
      PORT: 3000
      TZ: Asia/Tokyo
    container_name: my-mind
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-mind.rule=Host(`mm.notes.internal`)"
      - "traefik.http.routers.my-mind.middlewares=authelia@docker"


networks:
  traefik_net:
    external: true
volumes:
  data:
