services:
  my-mind:
    build: .
    #ports:
    #  - "3001:3000"
    volumes:
      - ./maps:/app/maps
    restart: unless-stopped
    environment:
      PORT: 3000
    container_name: my-mind
    networks:
      - traefik_br
    labels:
      - "traefik.enable=true" ###
      - "traefik.docker.network=traefik_br"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in-http.rule=Host(`${COMPOSE_PROJECT_NAME}.app.internal`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in-http.middlewares=force-https@file" ###
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in.rule=Host(`${COMPOSE_PROJECT_NAME}.app.internal`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-in.middlewares=hsts@file" ###
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
networks:
  traefik_br:
    external: true
